version: "3"

services:
  backend:
    build: ./backend
    container_name: flask_backend
    ports:
      - "6000:6000"

  frontend:
    build: ./frontend
    container_name: node_frontend
    ports:
      - "4000:4000"
    depends_on:
      - backend