name: Deploy Full App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}

          script: |
            set -e

            if [ -d ~/my-app ]; then
              rm -rf ~/my-app
            fi

            git clone https://github.com/dineshdsk8/flask-node-app.git ~/my-app

            cd ~/my-app

            docker compose down || true

            docker compose build --no-cache

            docker compose up -d